version: "3.8"

services:
  social_db:
    image: postgres:16.3
    container_name: social_db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - social-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  social-data:
